name: GitHub Actions Version Updater

# Controls when the action will run.
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # [Required] Access token with `workflow` scope.
          token: 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

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.1
        with:
          # [Required] Access token with `workflow` scope.
          token: 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
